CREATE TABLE IF NOT EXISTS FeedBack(
  IdFeedBack INT AUTO_INCREMENT PRIMARY KEY,
  IdUser INT NOT NULL,
  IdRecipe INT NOT NULL,
  Note INT NOT NULL,
  Text VARCHAR(300) NOT NULL,
  FOREIGN KEY (IdUser) REFERENCES Users(IdUser),
  FOREIGN KEY (IdRecipe) REFERENCES Recipe(IdRecipe)
) ENGINE = InnoDB;